[general]
live_config_reload = true

[env]
TERM = "alacritty"

[colors]
draw_bold_text_with_bright_colors = false

[font]
size = 10

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Bold"

[font.italic]
family = "FiraCode Nerd Font Mono"
style = "Italic"

[font.bold_italic]
family = "FiraCode Nerd Font Mono"
style = "Bold Italic"

[window]
decorations = "none"
dynamic_title = true
startup_mode = "Windowed"

[window.padding]
x = 5
y = 5

[keyboard]
bindings = [
  { key = "Return", mods = "Shift", chars = "\n" },
  # Send a unique escape sequence for Ctrl+Backspace (CSI 127 ; 5 u)
  # This allows Neovim to distinguish it from Ctrl+H
  { key = "Back", mods = "Control", chars = "\u001b[127;5u" },
]
