[settings]
experimental = true

[tools]
"pipx:basic-memory" = "0.15.2"
python = "3.13.3"
uv = "0.6.8"
nodejs="18.17.0"
yarn="1.22.19"
java="system"
act="0.2.31"
awscli="2.7.9"
fzf="0.34.0"
github-cli="2.31.0"
golang="1.18.3"
actionlint="1.6.20"
deno="1.36.0"
shfmt="3.6.0"
shellcheck="0.9.0"
bat="0.22.1"
ripgrep="13.0.0"
age="1.1.1"
zig="0.10.1"
kubectl="1.18.17"
terraform="1.5.2"
helm="3.10.0"
dotnet="7.0.306"
cmake="3.29.2"
rust="1.77.2"
jq="1.7.1"
lazygit="0.42.0"
jless="0.9.0"
"ubi:scottmckendry/pokemon-go-colorscripts" = "0.3.1"
neovim = "0.11.5"
starship = "1.24.0"
opencode = "1.0.78"
"ubi:mfontanini/presenterm" = "0.15.1"
