
[settings]
experimental = true

[tools]
"npm:chrome-devtools-mcp" = "0.10.2"
"pipx:basic-memory" = "0.15.2"
"ubi:asciinema/asciinema" = "3.0.1"
"ubi:mfontanini/presenterm" = "0.15.1"
"ubi:scottmckendry/pokemon-go-colorscripts" = "0.3.1"
act="0.2.31"
actionlint="1.6.20"
age="1.1.1"
ast-grep = "0.40.0"
awscli="2.7.9"
bat="0.22.1"
bun = "1.3.4"
cmake="3.29.2"
deno="1.36.0"
dotnet="7.0.306"
fzf="0.34.0"
github-cli= "2.83.0"
golang="1.18.3"
helm="3.10.0"
java= "23.0.2"
jless="0.9.0"
jq="1.7.1"
kubectl="1.18.17"
lazygit="0.42.0"
neovim = "0.11.5"
python = "3.13.3"
ripgrep="13.0.0"
rust= "1.92.0"
shellcheck="0.9.0"
shfmt="3.6.0"
starship = "1.24.0"
terraform="1.5.2"
uv = "0.6.8"
yarn="1.22.19"
zig="0.10.1"
node = "25.2.1"
"npm:in-memoria" = "latest"
"npm:mcporter" = "latest"
"npm:gtop" = "1.1.5"
bottom = "0.11.4"
go = "latest"
"cargo:zellij" = "0.43.1"
"npm:firefox-devtools-mcp" = "0.4.0"
"ubi:Lifailon/lazyjournal" = "0.8.2"
"ubi:Feel-ix-343/markdown-oxide" = "latest"
"ubi:zk-org/zk" = "latest"
glow = "latest"
dasel = "latest"
watchexec = "latest"
semver = "latest"
"pipx:homeassistant-cli" = "latest"
"ubi:dlvhdr/gh-dash" = "4.20.1"
"npm:gh-actions-language-server" = "0.0.3"
"npm:@scopecraft/cmd" = "latest"
"npm:browser-debugger-cli" = "alpha"
"npm:@mariozechner/pi-coding-agent" = "latest"

[tools."github:aristocratos/btop"]
version = "1.4.5"


[tools."github:anomalyco/opencode"]
version = "1.1.1"

[tools."github:anomalyco/opencode".platforms]
linux-x64 = { asset_pattern = "opencode-linux-x64.tar.gz" }
macos-arm64 = { asset_pattern = "opencode-darwin-x64.tar.gz" }
windows-x64 = { asset_pattern = "opencode-windows-x64.zip" }
