
[settings]
experimental = true

[tools]
"cargo:p1rallels/codemapper" = "latest"
"cargo:zellij" = "0.43.1"
"github:zenobi-us/opennotes" = "latest"
"go:github.com/Crosse/font-install" = "latest"
"npm:@mariozechner/pi-coding-agent" = "latest"
"npm:@mermaid-js/mermaid-cli" = "latest"
"npm:chrome-devtools-mcp" = "0.10.2"
"npm:firefox-devtools-mcp" = "0.4.0"
"npm:gh-actions-language-server" = "0.0.3"
"npm:gtop" = "1.1.5"
"npm:mcporter" = "latest"
"npm:surf-cli" = "latest"
"pipx:open-webui" = "latest"
"pipx:vllm" = "latest"
"pipx:vllm-playground" = "latest"
"ubi:Feel-ix-343/markdown-oxide" = "latest"
"ubi:asciinema/asciinema" = "3.0.1"
"ubi:dlvhdr/gh-dash" = "4.20.1"
"ubi:mfontanini/presenterm" = "0.15.1"
"ubi:scottmckendry/pokemon-go-colorscripts" = "0.3.1"
"ubi:terrastruct/d2" = "latest"
act="0.2.31"
actionlint="1.6.20"
age="1.1.1"
ast-grep = "0.40.0"
awscli="2.7.9"
bat="0.22.1"
bottom = "0.11.4"
btop = "latest"
bun = "latest"
cmake="3.29.2"
dasel = "latest"
deno="1.36.0"
dotnet="7.0.306"
fzf="0.34.0"
github-cli= "2.83.0"
glow = "latest"
go = "latest"
golang="1.18.3"
helm="3.10.0"
java= "23.0.2"
jless="0.9.0"
jq="1.7.1"
kubectl="1.18.17"
lazygit="0.42.0"
neovim = "0.11.5"
node = "lts"
python = "3.13.3"
ripgrep="13.0.0"
rust= "1.92.0"
semver = "latest"
shellcheck="0.9.0"
shfmt="3.6.0"
starship = "1.24.0"
terraform="1.5.2"
uv = "0.6.8"
watchexec = "latest"
yarn="1.22.19"
yt-dlp = "latest"
zig="0.10.1"

[tools."github:aristocratos/btop"]
version = "1.4.5"

