
[settings]
experimental = true

[tools]
"npm:chrome-devtools-mcp" = "0.10.2"
"pipx:basic-memory" = "0.15.2"
"ubi:asciinema/asciinema" = "3.0.1"
"ubi:mfontanini/presenterm" = "0.15.1"
"ubi:scottmckendry/pokemon-go-colorscripts" = "0.3.1"
"ubi:sst/opencode" = { version = "1.0.128", matching_regex = 'x64\.(tar\.gz|zip)$', matching = "opencode-linux-x64.tar.gz" }
act="0.2.31"
actionlint="1.6.20"
age="1.1.1"
ast-grep = "0.40.0"
awscli="2.7.9"
bat="0.22.1"
btop = "latest"
bun = "1.3.3"
cmake="3.29.2"
deno="1.36.0"
dotnet="7.0.306"
fzf="0.34.0"
github-cli= "2.83.0"
golang="1.18.3"
helm="3.10.0"
java="system"
jless="0.9.0"
jq="1.7.1"
kubectl="1.18.17"
lazygit="0.42.0"
neovim = "0.11.5"
node = "25.2.1"
nodejs="18.17.0"
python = "3.13.3"
ripgrep="13.0.0"
rust="1.77.2"
shellcheck="0.9.0"
shfmt="3.6.0"
starship = "1.24.0"
terraform="1.5.2"
uv = "0.6.8"
yarn="1.22.19"
zig="0.10.1"
zellij = "latest"
