[note]

filename = "{{id}}-{{slug title}}"
extension = "md"
# Configure random ID generation.

# The charset used for random IDs. You can use:
#   * letters: only letters from a to z.
#   * numbers: 0 to 9
#   * alphanum: letters + numbers
#   * hex: hexadecimal, from a to f and 0 to 9
#   * custom string: will use any character from the provided value
id-charset = "alphanum"

# Length of the generated IDs.
id-length = 8

# Letter case for the random IDs, among lower, upper or mixed.
id-case = "lower"

# EXTRA VARIABLES
#
# A dictionary of variables you can use for any custom values when generating
# new notes. They are accessible in templates with {{extra.<key>}}
[extra]
status = "todo"

[group.specs]
paths = ["1-specs/**"]
[group.specs.note]
template = "spec_template.md"
filename = "1-specs/{{id}}-{{slug title}}"
[group.specs.extra]
type = "spec"

[group.plans]
paths = ["2-plans/**"]
[group.plans.note]
template = "plan_template.md"
filename = "2-plans/{{id}}-{{slug title}}"
[group.plans.extra]
type = "plan"

[group.research]
paths = ["3-research/**"]
[group.research.note]
template = "research_template.md"
filename = "3-research/{{id}}-{{slug title}}"
[group.research.extra]
type = "research"

[group.decisions]
paths = ["4-decisions/**"]
[group.decisions.note]
template = "decision_template.md"
filename = "4-decisions/{{id}}-{{slug title}}"
[group.decisions.extra]
type = "decision"

[group.stories]
paths = ["5-stories/**"]
[group.stories.note]
template = "story_template.md"
filename = "5-stories/{{id}}-{{slug title}}"
[group.stories.extra]
type = "story"

[group.tasks]
paths = ["6-tasks/**"]
[group.tasks.note]
template = "task_template.md"
filename = "6-tasks/{{id}}-{{slug title}}"
[group.tasks.extra]
type = "task"


# MARKDOWN SETTINGS
[format.markdown]

# Format used to generate links between notes.
# Either "wiki", "markdown" or a custom template. Default is "markdown".
#link-format = "wiki"
# Indicates whether a link's path will be percent-encoded.
# Defaults to true for "markdown" format and false for "wiki" format.
#link-encode-path = true
# Indicates whether a link's path file extension will be removed.
# Defaults to true.
#link-drop-extension = true

# Enable support for #hashtags.
hashtags = false
# Enable support for :colon:separated:tags:.
colon-tags = false
# Enable support for Bear's #multi-word tags#
# Hashtags must be enabled for multi-word tags to work.
multiword-tags = false


# EXTERNAL TOOLS
[tool]

# Default editor used to open notes. When not set, the EDITOR or VISUAL
# environment variables are used.
editor = "nvim"

# Pager used to scroll through long output. If you want to disable paging
# altogether, set it to an empty string "".
#pager = "less -FIRX"

# Command used to preview a note during interactive fzf mode.
# Set it to an empty string "" to disable preview.

# bat is a great tool to render Markdown document with syntax highlighting.
#https://github.com/sharkdp/bat
fzf-preview = "glow {-1}"


# LSP
#
#   Configure basic editor integration for LSP-compatible editors.
#   See https://zk-org.github.io/zk/tips/editors-integration.html
#
[lsp]

[lsp.diagnostics]
# Each diagnostic can have for value: none, hint, info, warning, error

# Report titles of wiki-links as hints.
#wiki-title = "hint"
# Warn for dead links between notes.
dead-link = "error"
# Warn when a note links to itself.
#self-link = "warning"
# Report missing backlinks
missing-backlink = { level = "hint", position = "bottom" }


[lsp.completion]
# Customize the completion pop-up of your LSP client.

# Show the note title in the completion pop-up, or fallback on its path if empty.
#note-label = "{{title-or-path}}"
# Filter out the completion pop-up using the note title or its path.
#note-filter-text = "{{title}} {{path}}"
# Show the note filename without extension as detail.
#note-detail = "{{filename-stem}}"


# NAMED FILTERS
#
#    A named filter is a set of note filtering options used frequently together.
#
[filter]

# Matches the notes created the last two weeks. For example:
#    $ zk list recents --limit 15
#    $ zk edit recents --interactive
#recents = "--sort created- --created-after 'last two weeks'"


# COMMAND ALIASES
#
#   Aliases are user commands called with `zk <alias> [<flags>] [<args>]`.
#
#   The alias will be executed with `$SHELL -c`, please refer to your shell's
#   man page to see the available syntax. In most shells:
#     * $@ can be used to expand all the provided flags and arguments
#     * you can pipe commands together with the usual | character
#
[alias]
# Here are a few aliases to get you started.

plan = "zk new -W $ZK_NOTEBOOK_DIR --group plans --extra type=plan $@"
research = "zk new -W $ZK_NOTEBOOK_DIR --group research --extra type=research $@"
decision = "zk new -W $ZK_NOTEBOOK_DIR --group decisions --extra type=decision $@"
story = "zk new -W $ZK_NOTEBOOK_DIR --group stories --extra type=story $@"
task = "zk new -W $ZK_NOTEBOOK_DIR --group tasks --extra type=task $@"

# Shortcut to a command.
#ls = "zk list $@"

# Default flags for an existing command.
#list = "zk list --quiet $@"

# Edit the last modified note.
#editlast = "zk edit --limit 1 --sort modified- $@"

# Edit the notes selected interactively among the notes created the last two weeks.
# This alias doesn't take any argument, so we don't use $@.
#recent = "zk edit --sort created- --created-after 'last two weeks' --interactive"

# Print paths separated with colons for the notes found with the given
# arguments. This can be useful to expand a complex search query into a flag
# taking only paths. For example:
#   zk list --link-to "`zk path -m potatoe`"
#path = "zk list --quiet --format {{path}} --delimiter , $@"

# Show a random note.
#lucky = "zk list --quiet --format full --sort random --limit 1"

# Returns the Git history for the notes found with the given arguments.
# Note the use of a pipe and the location of $@.
#hist = "zk list --format path --delimiter0 --quiet $@ | xargs -t -0 git log --patch --"

# Edit this configuration file.
#conf = '$EDITOR "$ZK_NOTEBOOK_DIR/.zk/config.toml"'
